// ═══════════════════════════════════════════════════════
// CTRL-A — TOOL SCREENSHOT RESOLUTION
//
// The tool previews prefer a self-hosted screenshot living in
// `public/ctrla/toolshots/{id}.webp`. When a local shot is
// present it is used; otherwise the preview falls back to the
// third-party WordPress mShots service (see ToolPreview.tsx).
//
// Since a client component cannot cheaply probe the filesystem,
// a build-time manifest lists which tool ids currently have a
// local shot. The manifest is regenerated by
// `scripts/capture-toolshots.mjs` (run on the monthly volume
// pass). With an EMPTY manifest every tool falls back to
// mShots, so the mechanism ships working with zero shots.
//
// FILE CONVENTION: `public/ctrla/toolshots/{tool-id}.webp`
//   - format: .webp (single convention)
//   - id: `toolShotId(url)` — see below; the capture script uses
//     the exact same derivation so ids always line up.
// ═══════════════════════════════════════════════════════

import manifest from "../../../public/ctrla/toolshots/manifest.json";

/**
 * Stable, collision-free id for a tool derived from its URL.
 * Tools have no explicit `id` field, and a name can be re-worded,
 * so the host+path of the URL is the durable key.
 *
 * NOTE: keep this in exact sync with `toolShotId` in
 * `scripts/capture-toolshots.mjs`.
 *
 *   https://vercel.com/            -> "vercel-com"
 *   https://www.figma.com/design   -> "figma-com-design"
 */
export function toolShotId(url: string): string {
  return url
    .replace(/^https?:\/\//i, "")
    .replace(/^www\./i, "")
    .replace(/\/+$/, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const shotIds = new Set<string>(
  ((manifest as { shots?: string[] }).shots ?? []).map((s) => s.toLowerCase())
);

/**
 * Public path to a tool's self-hosted screenshot, or `null` when
 * no local shot exists yet (caller should fall back to mShots).
 */
export function localShot(url: string): string | null {
  const id = toolShotId(url);
  return shotIds.has(id) ? `/ctrla/toolshots/${id}.webp` : null;
}
